Update ja.json
ynoproject/ynobadges pull request #215
Opened 2022-11-18 20:40 UTC by uroyu

2022-11-19 16:26 UTC, Flashfyre requested changes

2022-11-19 16:26 UTC, Flashfyre commented on lang/ja.json
> +      "condition": "海底,バク,ケンキュウジョ(巨大),夢の夢部屋,逆さ宿(隠しエリア),赤い空の崖,拒絶,頭,赤黒迷路,色の無い谷,繫茂でもう一人のうろつきを目撃する"
Shouldn't these be using the full-width comma?

2022-11-19 23:29 UTC, uroyu commented on lang/ja.json
> +      "condition": "海底,バク,ケンキュウジョ(巨大),夢の夢部屋,逆さ宿(隠しエリア),赤い空の崖,拒絶,頭,赤黒迷路,色の無い谷,繫茂でもう一人のうろつきを目撃する"
OK

2022-11-21 06:35 UTC, Flashfyre approved these changes

2022-11-21 06:36 UTC, merged