Update zh.json
ynoproject/ynobadges pull request #497
Opened 2023-09-29 03:11 UTC by jacarandia28

2023-09-30 12:09 UTC, Flashfyre commented
Please update this so it does not remove badges

2023-10-02 14:31 UTC, nekocarpet commented on lang/zh.json
>      }
```suggestion
    },
    "arachnophobia_nest": {
      "name": "恐蛛症",
      "description": "Deep within the nest lies the queen and her hungry children.",
      "condition": "电锯 Spider Queen 并因此受困于 Spiders' Nest "
    },
    "giant_spider": {
      "name": "The Giant Enemy Spider",
      "condition": "在 Scenic Outlook 触发蛛网事件"
    },
    "bloody_house_illusive": {
      "name": "Narrow Your Eyes",
      "description": "她假装未察觉",
      "condition": "在 Illusive Forest 的 Bloody Eye House 中装备双马尾效果 "
    },
    "cataclysm_overgrown": {
      "name": "灭世之物",
      "description": "远古巨兽的遗骸",
      "condition": "在 Overgrown City 看见 The Thing That Ended the World"
    },
    "shinto_curse_chaser": {
      "name": "复仇诅咒",
      "condition": "在 Shinto Shrine 被抓住"
    },
    "teru_teru_bozu_pond": {
      "name": "晴天小塘",
      "description": "头上别再下雨啦！",
      "condition": "拜访 Teru Teru Bozu Pond"
    },
    "slide_park": {
      "name": "一人嬉戏",
      "description": "追尾巴转圈跑",
      "condition": "玩 Sculpture Park 的滑梯"
    }
```

2023-10-02 14:33 UTC, nekocarpet commented on lang/zh.json
>      }
```suggestion
    },
    "silent_laughter": {
      "name": "𝐍𝐨𝐭",
      "description": "没人认同你",
      "condition": "触发 Silent Laughter 事件"
    }
```

2023-10-02 14:35 UTC, nekocarpet requested changes
Supplemented missing lines. See suggested changes.

2023-10-02 19:42 UTC, Flashfyre approved these changes

2023-10-02 19:42 UTC, merged