Update to tr.json
ynoproject/ynobadges pull request #734
Opened 2024-06-07 02:08 UTC by Alpeel

About ~180 badges.
Also trying to see if I managed to figure out if I managed to figure out Github!

2024-06-07 18:34 UTC, Mimigris commented
Also, translating the names of the world isn't necessary a good idea since the location display and wiki link are in English, so this may confuse players when trying to search for info about specific contents.

2024-06-07 18:48 UTC, Mimigris requested changes

2024-06-07 18:48 UTC, Mimigris commented on lang/tr.json
> +      "condition": "YNOproject'de bulunan Yume Nikki Hayran Oyunlarını geliştir veya harita oluşturarak katkıda bulun",
You added a comma at the end of said line (line 112) that shouldn't be here

2024-06-07 18:48 UTC, Mimigris commented on lang/tr.json
> +      "name": "Michael Jackson",
I wonder if this reference may not be too direct, though I suppose it's up to you

2024-06-07 18:48 UTC, Mimigris commented on lang/tr.json
> +      "condition": "Río'nun dünyalarındaki 5 Kara Delik Kız'ın tamamını bul ve etkileşime geç. Eğer önceden bunu yaptıysan, onları bulduğun alanı tekrar ziyaret etmen gerekiyor"
This line is missing a dot at the end, not sure if it's intended

2024-06-07 18:48 UTC, Mimigris commented on lang/tr.json
> +      "description": "Dehşetlerin ve gölgelerin çarpık ormanında, mavi bir şey filizlenir doğada",
This line is also missing a dot, also unsure if it's intended

2024-06-07 22:37 UTC, Alpeel commented
> Also, translating the names of the world isn't necessary a good idea since the location display and wiki link are in English, so this may confuse players when trying to search for info about specific contents.

I see, I believed there would be a way to translate the UI element that links to the wiki to different localizations. Would it be better to scrub the world names back to their original at this point?

2024-06-08 08:36 UTC, Mimigris commented
While translating the names could be possible for games that are rather static like Yume Nikki, by creating new locations in the repository ynolocations, Yume 2kki is in constant evolution having new maps added and having to be translated each week, so it's globally not a good idea.

2024-06-08 08:57 UTC, Alpeel commented
That makes total sense. I will re-commit with the world names undone. This saves a ton of time since world names are by far the hardest to translate, so that is a plus I guess!

2024-06-09 12:03 UTC, Mimigris requested changes

2024-06-09 12:03 UTC, Mimigris commented on lang/tr.json
> +      "condition": Cosmic Cube World'e ulaş"
You removed a " at the start of this line

2024-06-21 16:33 UTC, Mimigris commented
The changes made in this pull request got added and merged with #749 and are now implemented on the site, so this pull request can safely be closed 👍

2024-06-22 00:10 UTC, closed without merging